### ISSUE TITLE
docs: Atualização do Readme 

### ISSUE THREAD

**Issue by zlimaz** [unb-mds/Mds-SitePesadelo#15]
## Descrição da Tarefa

É necessário que o readme esteja atualizado para que qualquer pessoa que entre no repositório, entenda qual é o projeto e objetivo dele

## Critérios de Aceitação

- [x] Colocar imagem dos membros
- [x] Explicar de forma breve o projeto
- [x] Colocar imagem da pesadelo
- [ ] 
- [ ] 

## Requisitos
A quais requisitos do projeto esta questão se refere?

- [](Não se relaciona com nenhum)

## Informações Adicionais

Sem informações adicionais

**Comment by drykette** [comment]
Todos os criterios de aceitação foram satisfeitos.
